import puppeteer from "puppeteer";
import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import OpenAI from "openai";
import { analyzeWebsite } from "../lib/analyze.mjs";
import { fileURLToPath } from "url";

dotenv.config();

const app = express();

// ---------------- CORS ----------------
// Allow local dev and deployed frontend (replace with actual frontend URL)
const allowedOrigins = [
  "http://localhost:3000",
  process.env.FRONTEND_URL, // e.g., https://your-frontend.vercel.app
];

app.use(cors({
  origin: function(origin, callback){
    if (!origin || allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error("Not allowed by CORS"));
    }
  }
}));

app.use(express.json());

// ✅ ES module __dirname fix
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------- Helper: Convert LLM text → clean HTML ----------------
function textToHTML(text) {
  const lines = text.split("\n");
  let html = "";
  let inList = false;

  for (let line of lines) {
    line = line.trim();
    if (!line) continue;

    // Remove Markdown formatting
    line = line.replace(/\*\*(.*?)\*\*/g, "$1");
    line = line.replace(/\*(.*?)\*/g, "$1");
    line = line.replace(/`(.*?)`/g, "$1");

    if (/^Client Information:/i.test(line)) continue;

    if (/^(Executive Summary|SEO Findings|Accessibility Review|Performance Review|Critical Issues|Actionable Recommendations)/i.test(line)) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h2>${line}</h2>`;
      continue;
    }

    if (/^-/.test(line)) {
      if (!inList) { html += "<ul>"; inList = true; }
      html += `<li>${line.replace(/^- /, "")}</li>`;
      continue;
    }

    if (inList) { html += "</ul>"; inList = false; }
    html += `<p>${line}</p>`;
  }

  if (inList) html += "</ul>";
  return html;
}

// ---------------- Routes ----------------

// Log requests (for debugging)
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url} - Origin: ${req.headers.origin}`);
  next();
});

// Route 1: Analyze website → JSON
app.post("/analyze", async (req, res) => {
  try {
    const { url } = req.body;
    if (!url) return res.status(400).json({ error: "URL is required" });

    const result = await analyzeWebsite(url);
    res.json(result);
  } catch (error) {
    console.error("Analysis Error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Route 2: Generate PDF
app.post("/report-pdf", async (req, res) => {
  try {
    const { data } = req.body;
    if (!data) return res.status(400).json({ error: "Missing analysis JSON" });

    const prompt = `
You are a professional website auditor.
Write a detailed audit report based on this JSON:

${JSON.stringify(data, null, 2)}

Include sections:
Executive Summary
SEO Findings
Accessibility Review
Performance Review
Critical Issues
Actionable Recommendations

Write in professional tone, plain text, no markdown.
`;

    const client = new OpenAI({
      baseURL: "https://router.huggingface.co/v1",
      apiKey: process.env.HUGGINGFACE_API_KEY,
    });

    const response = await client.chat.completions.create({
      model: "meta-llama/Llama-3.1-8B-Instruct:novita",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 1800,
    });

    const reportText = response.choices?.[0]?.message?.content?.trim() || "No content generated by LLM.";
    const formattedHTML = textToHTML(reportText);

    const templatePath = path.join(__dirname, "templates/report.html");
    let html = fs.readFileSync(templatePath, "utf8");

    html = html
      .replace("{{url}}", data.url)
      .replace("{{date}}", new Date().toLocaleDateString())
      .replace("{{{reportText}}}", formattedHTML);

    const browser = await puppeteer.launch({ headless: true, args: ["--no-sandbox"] });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=Synaphis_Website_Audit.pdf`);
    res.send(pdfBuffer);

  } catch (error) {
    console.error("PDF Generation Error:", error);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
});

// ---------------- Start server ----------------
const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log(`✅ Analyzer backend running on http://localhost:${PORT}`));
